#!/usr/bin/env -S npx tsx

/** Emit the whole league-history load as one portable SQL transaction. */

import {
  parseFranchises,
  parseManagers,
  parseManagerSeasons,
  parseSeasonResults,
} from '../lib/manual-history.ts';
import { readArchiveFile } from '../lib/history-files.ts';

function literal(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Refusing to emit ${value} as a SQL number.`);
    return String(value);
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function upsert(
  table: string, columns: string[], rows: Record<string, unknown>[], conflictKey: string[]
): string {
  if (rows.length === 0) return '';
  const tuples = rows.map(
    (row) => `  (${columns.map((column) => literal(row[column] ?? null)).join(', ')})`
  );
  const updatable = columns.filter((column) => !conflictKey.includes(column));
  const setClause = updatable.length
    ? `do update set ${updatable.map((c) => `${c} = excluded.${c}`).join(', ')}`
    : 'do nothing';
  return `insert into ${table} (${columns.join(', ')}) values\n${tuples.join(',\n')}\n` +
    `on conflict (${conflictKey.join(', ')}) ${setClause};`;
}

const franchises = parseFranchises(readArchiveFile('franchises.csv'));
const managers = parseManagers(readArchiveFile('managers.csv'));
const seasons = parseSeasonResults(readArchiveFile('season-results.csv'));
const managerSeasons = parseManagerSeasons(readArchiveFile('manager-seasons.csv'));
const seasonTeams = seasons.map(({ season, franchise_key, team_name, espn_team_id }) => ({
  season, franchise_key, team_name, espn_team_id,
}));
const seasonResults = seasons.map(({ team_name: _name, espn_team_id: _id, ...result }) => result);

const years = seasons.map((row) => row.season);
const blocks = [
  `-- League history, ${Math.min(...years)}-${Math.max(...years)}.`,
  `-- Generated by scripts/history-load-sql.ts -- do not edit by hand.`,
  `-- ${franchises.length} franchises, ${managers.length} managers, ` +
  `${seasons.length} season results, ${managerSeasons.length} manager assignments.`,
  `-- Idempotent: every statement is an upsert, so re-running changes nothing.`,
  '',
  'begin;',
  '',
  upsert('public.franchises',
    ['franchise_key', 'current_name', 'founded_season', 'folded_season', 'notes'],
    franchises, ['franchise_key']),
  '',
  upsert('public.managers', ['manager_key', 'display_name', 'notes'], managers, ['manager_key']),
  '',
  upsert('public.franchise_season_teams',
    ['season', 'franchise_key', 'team_name', 'espn_team_id'],
    seasonTeams, ['season', 'franchise_key']),
  '',
  upsert('public.franchise_season_results',
    [
      'season', 'franchise_key', 'regular_wins', 'regular_losses', 'regular_ties',
      'regular_points_for', 'regular_points_against', 'playoff_wins', 'playoff_losses',
      'final_place', 'is_champion', 'is_runner_up', 'source', 'source_note',
    ],
    seasonResults, ['season', 'franchise_key']),
  '',
  upsert('public.manager_franchise_seasons',
    ['season', 'manager_key', 'franchise_key', 'is_primary'],
    managerSeasons, ['season', 'manager_key', 'franchise_key']),
  '',
  'commit;',
  '',
];

process.stdout.write(blocks.join('\n'));
