#!/usr/bin/env -S npx tsx

/**
 * Emit the whole league-history load as one portable SQL transaction.
 *
 * `import-manual-history.ts` needs a Postgres connection string. This does the
 * same work as a .sql file instead, so the load can go through anything that
 * runs SQL -- the Neon MCP connector, `scripts/neon-sql.mjs`, psql, or the Neon
 * console -- without a credential reaching this machine.
 *
 * The statements are the same idempotent upserts the importer builds, so
 * running this twice is a no-op the second time.
 *
 *   npx tsx scripts/history-load-sql.ts > load.sql
 */

import {
  parseFranchises,
  parseManagers,
  parseManagerSeasons,
  parseSeasonResults,
} from '../lib/manual-history.ts';
import { readArchiveFile } from '../lib/history-files.ts';

/** SQL literals, quoted here because these values are inlined, not bound. */
function literal(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Refusing to emit ${value} as a SQL number.`);
    return String(value);
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function upsert(
  table: string, columns: string[], rows: Record<string, unknown>[], conflictKey: string[]
): string {
  if (rows.length === 0) return '';
  const tuples = rows.map(
    (row) => `  (${columns.map((column) => literal(row[column] ?? null)).join(', ')})`
  );
  const updatable = columns.filter((column) => !conflictKey.includes(column));
  const setClause = updatable.length
    ? `do update set ${updatable.map((c) => `${c} = excluded.${c}`).join(', ')}`
    : 'do nothing';
  return `insert into ${table} (${columns.join(', ')}) values\n${tuples.join(',\n')}\n` +
    `on conflict (${conflictKey.join(', ')}) ${setClause};`;
}

const franchises = parseFranchises(readArchiveFile('franchises.csv'));
const managers = parseManagers(readArchiveFile('managers.csv'));
const seasons = parseSeasonResults(readArchiveFile('season-results.csv'));
const managerSeasons = parseManagerSeasons(readArchiveFile('manager-seasons.csv'));

const years = seasons.map((row) => row.season);
const blocks = [
  `-- League history, ${Math.min(...years)}-${Math.max(...years)}.`,
  `-- Generated by scripts/history-load-sql.ts -- do not edit by hand.`,
  `-- ${franchises.length} franchises, ${managers.length} managers, ` +
  `${seasons.length} season results, ${managerSeasons.length} manager assignments.`,
  `-- Idempotent: every statement is an upsert, so re-running changes nothing.`,
  '',
  'begin;',
  '',
  upsert(
    'public.franchises',
    ['franchise_key', 'current_name', 'founded_season', 'folded_season', 'notes'],
    franchises, ['franchise_key']
  ),
  '',
  upsert(
    'public.managers',
    ['manager_key', 'display_name', 'notes'],
    managers, ['manager_key']
  ),
  '',
  upsert(
    'public.franchise_seasons',
    [
      'season', 'franchise_key', 'team_name', 'espn_team_id', 'regular_wins',
      'regular_losses', 'regular_ties', 'regular_points_for', 'regular_points_against',
      'playoff_wins', 'playoff_losses', 'final_place', 'is_champion', 'is_runner_up',
      'source', 'source_note',
    ],
    seasons, ['season', 'franchise_key']
  ),
  '',
  upsert(
    'public.manager_franchise_seasons',
    ['season', 'manager_key', 'franchise_key', 'is_primary'],
    managerSeasons, ['season', 'manager_key', 'franchise_key']
  ),
  '',
  'commit;',
  '',
];

process.stdout.write(blocks.join('\n'));
